
<%pre
    import cryptography.x509

    import cryptography.hazmat.primitives.asymmetric.ec
    import cryptography.hazmat.primitives.asymmetric.rsa
    import cryptography.hazmat.primitives.asymmetric.padding

    import cryptography.hazmat.primitives.ciphers
    import cryptography.hazmat.primitives.ciphers.algorithms

    import cryptography.hazmat.primitives.hashes

    import cryptography.hazmat.primitives.serialization

    import cryptography.exceptions
%>

// Weak
CIPHER_SUITE_RSA_WITH_NULL_MD5:
    \x00 \x01
    <%
    $keyex  = cryptography.hazmat.primitives.asymmetric.rsa
    $cipher = None
    $hash   = cryptography.hazmat.primitives.hashes.MD5
    %>
    ;

// Weak
CIPHER_SUITE_RSA_WITH_NULL_SHA:
    \x00 \x02
    <%
    $keyex  = cryptography.hazmat.primitives.asymmetric.rsa
    $cipher = None
    $hash   = cryptography.hazmat.primitives.hashes.SHA1
    %>
    ;

CIPHER_SUITE_RSA_WITH_RC4_128_MD5:
    \x00 \x04
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_RSA_WITH_RC4_128_SHA:
    \x00 \x05
    <%
    raise NotImplementedError
    %>
    ;

// Weak! Not in TLS 1.2
CIPHER_SUITE_RSA_WITH_DES_CBC_SHA:
    \x00 \x09
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_RSA_WITH_3DES_EDE_CBC_SHA:
    \x00 \x0A
    <%
    $keyex  = cryptography.hazmat.primitives.asymmetric.rsa
    $cipher = cryptography.hazmat.primitives.ciphers.algorithms.TripleDES
    $hash   = cryptography.hazmat.primitives.hashes.SHA1
    %>
    ;

// Weak! Not in TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_DES_CBC_SHA:
    \x00 \x15
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_DHE_RSA_WITH_3DES_EDE_CBC_SHA:
    \x00 \x16
    <%
    raise NotImplementedError
    %>
    ;

// Weak!
CIPHER_SUITE_PSK_WITH_NULL_SHA:
    \x00 \x2C
    <%
    raise NotImplementedError
    %>
    ;

// Weak!
CIPHER_SUITE_DHE_PSK_WITH_NULL_SHA:
    \x00 \x2D
    <%
    raise NotImplementedError
    %>
    ;

// Weak!
CIPHER_SUITE_RSA_PSK_WITH_NULL_SHA:
    \x00 \x2E
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_RSA_WITH_AES_128_CBC_SHA:
    \x00 \x2F
    <%
    $keyex  = cryptography.hazmat.primitives.asymmetric.rsa
    $cipher = cryptography.hazmat.primitives.ciphers.algorithms.TripleDES
    $hash   = cryptography.hazmat.primitives.hashes.SHA1
    %>
    ;

CIPHER_SUITE_DHE_RSA_WITH_AES_128_CBC_SHA:
    \x00 \x33
    <%
    $keyex  = cryptography.hazmat.primitives.asymmetric.rsa
    $cipher = cryptography.hazmat.primitives.ciphers.algorithms.AES
    $hash   = cryptography.hazmat.primitives.hashes.SHA1
    %>
    ;

CIPHER_SUITE_RSA_WITH_AES_256_CBC_SHA:
    \x00 \x35
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_DHE_RSA_WITH_AES_256_CBC_SHA:
    \x00 \x39
    <%
    raise NotImplementedError
    %>
    ;

// Weak!
CIPHER_SUITE_RSA_WITH_NULL_SHA256:
    \x00 \x3B
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_AES_128_CBC_SHA256:
    \x00 \x3C
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_AES_256_CBC_SHA256:
    \x00 \x3D
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_RSA_WITH_CAMELLIA_128_CBC_SHA:
    \x00 \x41
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA:
    \x00 \x45
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_AES_128_CBC_SHA256:
    \x00 \x67
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_AES_256_CBC_SHA256:
    \x00 \x6B
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_RSA_WITH_CAMELLIA_256_CBC_SHA:
    \x00 \x84
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA:
    \x00 \x88
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_PSK_WITH_RC4_128_SHA:
    \x00 \x8A
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_PSK_WITH_3DES_EDE_CBC_SHA:
    \x00 \x8B
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_PSK_WITH_AES_128_CBC_SHA:
    \x00 \x8C
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_PSK_WITH_AES_256_CBC_SHA:
    \x00 \x8D
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_DHE_PSK_WITH_RC4_128_SHA:
    \x00 \x8E
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_DHE_PSK_WITH_3DES_EDE_CBC_SHA:
    \x00 \x8F
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_DHE_PSK_WITH_AES_128_CBC_SHA:
    \x00 \x90
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_DHE_PSK_WITH_AES_256_CBC_SHA:
    \x00 \x91
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_RSA_PSK_WITH_RC4_128_SHA:
    \x00 \x92
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_RSA_PSK_WITH_3DES_EDE_CBC_SHA:
    \x00 \x93
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_RSA_PSK_WITH_AES_128_CBC_SHA:
    \x00 \x94
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_RSA_PSK_WITH_AES_256_CBC_SHA:
    \x00 \x95
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_AES_128_GCM_SHA256:
    \x00 \x9C
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_AES_256_GCM_SHA384:
    \x00 \x9D
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_AES_128_GCM_SHA256:
    \x00 \x9E
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_AES_256_GCM_SHA384:
    \x00 \x9F
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_PSK_WITH_AES_128_GCM_SHA256:
    \x00 \xA8
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_PSK_WITH_AES_256_GCM_SHA384:
    \x00 \xA9
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_AES_128_GCM_SHA256:
    \x00 \xAA
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_AES_256_GCM_SHA384:
    \x00 \xAB
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_AES_128_GCM_SHA256:
    \x00 \xAC
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_AES_256_GCM_SHA384:
    \x00 \xAD
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_PSK_WITH_AES_128_CBC_SHA256:
    \x00 \xAE
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_PSK_WITH_AES_256_CBC_SHA384:
    \x00 \xAF
    <%
    raise NotImplementedError
    %>
    ;

// Weak!
CIPHER_SUITE_PSK_WITH_NULL_SHA256:
    \x00 \xB0
    <%
    raise NotImplementedError
    %>
    ;

// Weak!
CIPHER_SUITE_PSK_WITH_NULL_SHA384:
    \x00 \xB1
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_DHE_PSK_WITH_AES_128_CBC_SHA256:
    \x00 \xB2
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_DHE_PSK_WITH_AES_256_CBC_SHA384:
    \x00 \xB3
    <%
    raise NotImplementedError
    %>
    ;

// Weak!
CIPHER_SUITE_DHE_PSK_WITH_NULL_SHA256:
    \x00 \xB4
    <%
    raise NotImplementedError
    %>
    ;

// Weak!
CIPHER_SUITE_DHE_PSK_WITH_NULL_SHA384:
    \x00 \xB5
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_RSA_PSK_WITH_AES_128_CBC_SHA256:
    \x00 \xB6
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_RSA_PSK_WITH_AES_256_CBC_SHA384:
    \x00 \xB7
    <%
    raise NotImplementedError
    %>
    ;

// Weak!
CIPHER_SUITE_RSA_PSK_WITH_NULL_SHA256:
    \x00 \xB8
    <%
    raise NotImplementedError
    %>
    ;

// Weak!
CIPHER_SUITE_RSA_PSK_WITH_NULL_SHA384:
    \x00 \xB9
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_CAMELLIA_128_CBC_SHA256:
    \x00 \xBA
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256:
    \x00 \xBE
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_CAMELLIA_256_CBC_SHA256:
    \x00 \xC0
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256:
    \x00 \xC4
    <%
    raise NotImplementedError
    %>
    ;

// Weak!
CIPHER_SUITE_ECDH_ECDSA_WITH_NULL_SHA:
    \xC0 \x01
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDH_ECDSA_WITH_RC4_128_SHA:
    \xC0 \x02
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA:
    \xC0 \x03
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDH_ECDSA_WITH_AES_128_CBC_SHA:
    \xC0 \x04
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDH_ECDSA_WITH_AES_256_CBC_SHA:
    \xC0 \x05
    <%
    raise NotImplementedError
    %>
    ;

// Weak!
CIPHER_SUITE_ECDHE_ECDSA_WITH_NULL_SHA:
    \xC0 \x06
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_ECDSA_WITH_RC4_128_SHA:
    \xC0 \x07
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA:
    \xC0 \x08
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_128_CBC_SHA:
    \xC0 \x09
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_256_CBC_SHA:
    \xC0 \x0A
    <%
    raise NotImplementedError
    %>
    ;

// Weak!
CIPHER_SUITE_ECDH_RSA_WITH_NULL_SHA:
    \xC0 \x0B
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDH_RSA_WITH_RC4_128_SHA:
    \xC0 \x0C
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDH_RSA_WITH_3DES_EDE_CBC_SHA:
    \xC0 \x0D
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDH_RSA_WITH_AES_128_CBC_SHA:
    \xC0 \x0E
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDH_RSA_WITH_AES_256_CBC_SHA:
    \xC0 \x0F
    <%
    raise NotImplementedError
    %>
    ;

// Weak!
CIPHER_SUITE_ECDHE_RSA_WITH_NULL_SHA:
    \xC0 \x10
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_RSA_WITH_RC4_128_SHA:
    \xC0 \x11
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA:
    \xC0 \x12
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_RSA_WITH_AES_128_CBC_SHA:
    \xC0 \x13
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_RSA_WITH_AES_256_CBC_SHA:
    \xC0 \x14
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256:
    \xC0 \x23
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384:
    \xC0 \x24
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_AES_128_CBC_SHA256:
    \xC0 \x25
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_AES_256_CBC_SHA384:
    \xC0 \x26
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_AES_128_CBC_SHA256:
    \xC0 \x27
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_AES_256_CBC_SHA384:
    \xC0 \x28
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_AES_128_CBC_SHA256:
    \xC0 \x29
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_AES_256_CBC_SHA384:
    \xC0 \x2A
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:
    \xC0 \x2B
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:
    \xC0 \x2C
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_AES_128_GCM_SHA256:
    \xC0 \x2D
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_AES_256_GCM_SHA384:
    \xC0 \x2E
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_AES_128_GCM_SHA256:
    \xC0 \x2F
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_AES_256_GCM_SHA384:
    \xC0 \x30
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_AES_128_GCM_SHA256:
    \xC0 \x31
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_AES_256_GCM_SHA384:
    \xC0 \x32
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_RC4_128_SHA:
    \xC0 \x33
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_3DES_EDE_CBC_SHA:
    \xC0 \x34
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_AES_128_CBC_SHA:
    \xC0 \x35
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_AES_256_CBC_SHA:
    \xC0 \x36
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_AES_128_CBC_SHA256:
    \xC0 \x37
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_AES_256_CBC_SHA384:
    \xC0 \x38
    <%
    raise NotImplementedError
    %>
    ;

// Weak! No SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_NULL_SHA:
    \xC0 \x39
    <%
    raise NotImplementedError
    %>
    ;

// Weak! No SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_NULL_SHA256:
    \xC0 \x3A
    <%
    raise NotImplementedError
    %>
    ;

// Weak! No SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_NULL_SHA384:
    \xC0 \x3B
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_ARIA_128_CBC_SHA256:
    \xC0 \x3C
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_ARIA_256_CBC_SHA384:
    \xC0 \x3D
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_ARIA_128_CBC_SHA256:
    \xC0 \x44
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_ARIA_256_CBC_SHA384:
    \xC0 \x45
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_ARIA_128_CBC_SHA256:
    \xC0 \x48
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_ARIA_256_CBC_SHA384:
    \xC0 \x49
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_ARIA_128_CBC_SHA256:
    \xC0 \x4A
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_ARIA_256_CBC_SHA384:
    \xC0 \x4B
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_ARIA_128_CBC_SHA256:
    \xC0 \x4C
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_ARIA_256_CBC_SHA384:
    \xC0 \x4D
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_ARIA_128_CBC_SHA256:
    \xC0 \x4E
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_ARIA_256_CBC_SHA384:
    \xC0 \x4F
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_ARIA_128_GCM_SHA256:
    \xC0 \x50
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_ARIA_256_GCM_SHA384:
    \xC0 \x51
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_ARIA_128_GCM_SHA256:
    \xC0 \x52
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_ARIA_256_GCM_SHA384:
    \xC0 \x53
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256:
    \xC0 \x5C
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_ARIA_256_GCM_SHA384:
    \xC0 \x5D
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_ARIA_128_GCM_SHA256:
    \xC0 \x5E
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_ARIA_256_GCM_SHA384:
    \xC0 \x5F
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_ARIA_128_GCM_SHA256:
    \xC0 \x60
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_ARIA_256_GCM_SHA384:
    \xC0 \x61
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_ARIA_128_GCM_SHA256:
    \xC0 \x62
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_ARIA_256_GCM_SHA384:
    \xC0 \x63
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_PSK_WITH_ARIA_128_CBC_SHA256:
    \xC0 \x64
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_PSK_WITH_ARIA_256_CBC_SHA384:
    \xC0 \x65
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_ARIA_128_CBC_SHA256:
    \xC0 \x66
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_ARIA_256_CBC_SHA384:
    \xC0 \x67
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_ARIA_128_CBC_SHA256:
    \xC0 \x68
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_ARIA_256_CBC_SHA384:
    \xC0 \x69
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_PSK_WITH_ARIA_128_GCM_SHA256:
    \xC0 \x6A
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_PSK_WITH_ARIA_256_GCM_SHA384:
    \xC0 \x6B
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_ARIA_128_GCM_SHA256:
    \xC0 \x6C
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_ARIA_256_GCM_SHA384:
    \xC0 \x6D
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_ARIA_128_GCM_SHA256:
    \xC0 \x6E
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_ARIA_256_GCM_SHA384:
    \xC0 \x6F
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_PSK_WITH_ARIA_128_CBC_SHA256:
    \xC0 \x70
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_PSK_WITH_ARIA_256_CBC_SHA384:
    \xC0 \x71
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_ECDSA_WITH_CAMELLIA_128_CBC_SHA256:
    \xC0 \x72
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_ECDSA_WITH_CA:
    \xC0 \x73
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDH_ECDSA_WITH_CAM:
    \xC0 \x74
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDH_ECDSA_WITH_CAMELLIA_256_CBC_SHA384:
    \xC0 \x75
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_RSA_WITH_CAMELLIA_128_CBC_SHA256:
    \xC0 \x76
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_RSA_WITH_CAMELLIA_256_CBC_SHA384:
    \xC0 \x77
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDH_RSA_WITH_CAMELLIA_128_CBC_SHA256:
    \xC0 \x78
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDH_RSA_WITH_CAMELLIA_256_CBC_SHA384:
    \xC0 \x79
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_CAMELLIA_128_GCM_SHA256:
    \xC0 \x7A
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_CAMELLIA_256_GCM_SHA384:
    \xC0 \x7B
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_CAMELLIA_128_GCM_SHA256:
    \xC0 \x7C
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_CAMELLIA_256_GCM_SHA384:
    \xC0 \x7D
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_CAMELLIA_128_GCM_SHA256:
    \xC0 \x86
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_CAMELLI:
    \xC0 \x87
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_CAMELLIA:
    \xC0 \x88
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_CAMELLIA_256_GCM_SHA384:
    \xC0 \x89
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_CAMELLIA_128_GCM_SHA256:
    \xC0 \x8A
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_CAMELLIA_256_GCM_SHA384:
    \xC0 \x8B
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_CAMELLIA_128_GCM_SHA256:
    \xC0 \x8C
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_CAMELLIA_256_GCM_SHA384:
    \xC0 \x8D
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_PSK_WITH_CAMELLIA_128_GCM_SHA256:
    \xC0 \x8E
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_PSK_WITH_CAMELLIA_256_GCM_SHA384:
    \xC0 \x8F
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_CAMELLIA_128_GCM_SHA256:
    \xC0 \x90
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_CAMELLIA_256_GCM_SHA384:
    \xC0 \x91
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_CAMELLIA_128_GCM_SHA256:
    \xC0 \x92
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_CAMELLIA_256_GCM_SHA384:
    \xC0 \x93
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_PSK_WITH_CAMELLIA_128_CBC_SHA256:
    \xC0 \x94
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_PSK_WITH_CAMELLIA_256_CBC_SHA384:
    \xC0 \x95
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_DHE_PSK_WITH_CAMELLIA_128_CBC_SHA256:
    \xC0 \x96
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_DHE_PSK_WITH_CAMELLIA_256_CBC_SHA384:
    \xC0 \x97
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_RSA_PSK_WITH_CAMELLIA_128_CBC_SHA256:
    \xC0 \x98
    <%
    raise NotImplementedError
    %>
    ;

CIPHER_SUITE_RSA_PSK_WITH_CAMELLIA_256_CBC_SHA384:
    \xC0 \x99
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_CAMELLIA_128_CBC_SHA256:
    \xC0 \x9A
    <%
    raise NotImplementedError
    %>
    ;

// Not in SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_CAMELLIA_256_CBC_SHA384:
    \xC0 \x9B
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_AES_128_CCM:
    \xC0 \x9C
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_AES_256_CCM:
    \xC0 \x9D
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_AES_128_CCM:
    \xC0 \x9E
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_AES_256_CCM:
    \xC0 \x9F
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_AES_128_CCM_8:
    \xC0 \xA0
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_WITH_AES_256_CCM_8:
    \xC0 \xA1
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_AES_128_CCM_8:
    \xC0 \xA2
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_AES_256_CCM_8:
    \xC0 \xA3
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_PSK_WITH_AES_128_CCM:
    \xC0 \xA4
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_PSK_WITH_AES_256_CCM:
    \xC0 \xA5
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_AES_128_CCM:
    \xC0 \xA6
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_AES_256_CCM:
    \xC0 \xA7
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_PSK_WITH_AES_128_CCM_8:
    \xC0 \xA8
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_PSK_WITH_AES_256_CCM_8:
    \xC0 \xA9
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_AES_128_CCM_8:
    \xC0 \xAA
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_AES_256_CCM_8:
    \xC0 \xAB
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_128_CCM:
    \xC0 \xAC
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_256_CCM:
    \xC0 \xAD
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_128_CCM_8:
    \xC0 \xAE
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_256_CCM_8:
    \xC0 \xAF
    <%
    raise NotImplementedError
    %>
    ;

// experimental
CIPHER_SUITE_ECJPAKE_WITH_AES_128_CCM_8:
    \xC0 \xFF
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256:
    \xCC \xA8
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256:
    \xCC \xA9
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_CHACHA20_POLY:
    \xCC \xAA
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_PSK_WITH_CHACHA20_POLY1305_SHA256:
    \xCC \xAB
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256:
    \xCC \xAC
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_CHACHA20_POLY1305_SHA256:
    \xCC \xAD
    <%
    raise NotImplementedError
    %>
    ;

// TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_CHACHA20_POLY1305_SHA256:
    \xCC \xAE
    <%
    raise NotImplementedError
    %>
    ;
