
CIPHER_SUITE_RSA_WITH_NULL_MD5:                             \x00 \x01; // Weak
CIPHER_SUITE_RSA_WITH_NULL_SHA:                             \x00 \x02; // Weak
CIPHER_SUITE_RSA_WITH_RC4_128_MD5:                          \x00 \x04;
CIPHER_SUITE_RSA_WITH_RC4_128_SHA:                          \x00 \x05;
CIPHER_SUITE_RSA_WITH_DES_CBC_SHA:                          \x00 \x09; // Weak! Not in TLS 1.2
CIPHER_SUITE_RSA_WITH_3DES_EDE_CBC_SHA:                     \x00 \x0A;
CIPHER_SUITE_DHE_RSA_WITH_DES_CBC_SHA:                      \x00 \x15; // Weak! Not in TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_3DES_EDE_CBC_SHA:                 \x00 \x16;
CIPHER_SUITE_PSK_WITH_NULL_SHA:                             \x00 \x2C; // Weak!
CIPHER_SUITE_DHE_PSK_WITH_NULL_SHA:                         \x00 \x2D; // Weak!
CIPHER_SUITE_RSA_PSK_WITH_NULL_SHA:                         \x00 \x2E; // Weak!
CIPHER_SUITE_RSA_WITH_AES_128_CBC_SHA:                      \x00 \x2F;
CIPHER_SUITE_DHE_RSA_WITH_AES_128_CBC_SHA:                  \x00 \x33;
CIPHER_SUITE_RSA_WITH_AES_256_CBC_SHA:                      \x00 \x35;
CIPHER_SUITE_DHE_RSA_WITH_AES_256_CBC_SHA:                  \x00 \x39;
CIPHER_SUITE_RSA_WITH_NULL_SHA256:                          \x00 \x3B; // Weak!
CIPHER_SUITE_RSA_WITH_AES_128_CBC_SHA256:                   \x00 \x3C; // TLS 1.2
CIPHER_SUITE_RSA_WITH_AES_256_CBC_SHA256:                   \x00 \x3D; // TLS 1.2
CIPHER_SUITE_RSA_WITH_CAMELLIA_128_CBC_SHA:                 \x00 \x41;
CIPHER_SUITE_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA:             \x00 \x45;
CIPHER_SUITE_DHE_RSA_WITH_AES_128_CBC_SHA256:               \x00 \x67;   // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_AES_256_CBC_SHA256:               \x00 \x6B;   // TLS 1.2
CIPHER_SUITE_RSA_WITH_CAMELLIA_256_CBC_SHA:                 \x00 \x84;
CIPHER_SUITE_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA:             \x00 \x88;
CIPHER_SUITE_PSK_WITH_RC4_128_SHA:                          \x00 \x8A;
CIPHER_SUITE_PSK_WITH_3DES_EDE_CBC_SHA:                     \x00 \x8B;
CIPHER_SUITE_PSK_WITH_AES_128_CBC_SHA:                      \x00 \x8C;
CIPHER_SUITE_PSK_WITH_AES_256_CBC_SHA:                      \x00 \x8D;
CIPHER_SUITE_DHE_PSK_WITH_RC4_128_SHA:                      \x00 \x8E;
CIPHER_SUITE_DHE_PSK_WITH_3DES_EDE_CBC_SHA:                 \x00 \x8F;
CIPHER_SUITE_DHE_PSK_WITH_AES_128_CBC_SHA:                  \x00 \x90;
CIPHER_SUITE_DHE_PSK_WITH_AES_256_CBC_SHA:                  \x00 \x91;
CIPHER_SUITE_RSA_PSK_WITH_RC4_128_SHA:                      \x00 \x92;
CIPHER_SUITE_RSA_PSK_WITH_3DES_EDE_CBC_SHA:                 \x00 \x93;
CIPHER_SUITE_RSA_PSK_WITH_AES_128_CBC_SHA:                  \x00 \x94;
CIPHER_SUITE_RSA_PSK_WITH_AES_256_CBC_SHA:                  \x00 \x95;
CIPHER_SUITE_RSA_WITH_AES_128_GCM_SHA256:                   \x00 \x9C;   // TLS 1.2
CIPHER_SUITE_RSA_WITH_AES_256_GCM_SHA384:                   \x00 \x9D;   // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_AES_128_GCM_SHA256:               \x00 \x9E;   // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_AES_256_GCM_SHA384:               \x00 \x9F;   // TLS 1.2
CIPHER_SUITE_PSK_WITH_AES_128_GCM_SHA256:                   \x00 \xA8;   // TLS 1.2
CIPHER_SUITE_PSK_WITH_AES_256_GCM_SHA384:                   \x00 \xA9;   // TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_AES_128_GCM_SHA256:               \x00 \xAA;   // TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_AES_256_GCM_SHA384:               \x00 \xAB;   // TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_AES_128_GCM_SHA256:               \x00 \xAC;   // TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_AES_256_GCM_SHA384:               \x00 \xAD;   // TLS 1.2
CIPHER_SUITE_PSK_WITH_AES_128_CBC_SHA256:                   \x00 \xAE;
CIPHER_SUITE_PSK_WITH_AES_256_CBC_SHA384:                   \x00 \xAF;
CIPHER_SUITE_PSK_WITH_NULL_SHA256:                          \x00 \xB0;   // Weak!
CIPHER_SUITE_PSK_WITH_NULL_SHA384:                          \x00 \xB1;   // Weak!
CIPHER_SUITE_DHE_PSK_WITH_AES_128_CBC_SHA256:               \x00 \xB2;
CIPHER_SUITE_DHE_PSK_WITH_AES_256_CBC_SHA384:               \x00 \xB3;
CIPHER_SUITE_DHE_PSK_WITH_NULL_SHA256:                      \x00 \xB4;   // Weak!
CIPHER_SUITE_DHE_PSK_WITH_NULL_SHA384:                      \x00 \xB5;   // Weak!
CIPHER_SUITE_RSA_PSK_WITH_AES_128_CBC_SHA256:               \x00 \xB6;
CIPHER_SUITE_RSA_PSK_WITH_AES_256_CBC_SHA384:               \x00 \xB7;
CIPHER_SUITE_RSA_PSK_WITH_NULL_SHA256:                      \x00 \xB8;   // Weak!
CIPHER_SUITE_RSA_PSK_WITH_NULL_SHA384:                      \x00 \xB9;   // Weak!
CIPHER_SUITE_RSA_WITH_CAMELLIA_128_CBC_SHA256:              \x00 \xBA;   // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256:          \x00 \xBE;   // TLS 1.2
CIPHER_SUITE_RSA_WITH_CAMELLIA_256_CBC_SHA256:              \x00 \xC0;   // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256:          \x00 \xC4;   // TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_NULL_SHA:                      \xC0 \x01; // Weak!
CIPHER_SUITE_ECDH_ECDSA_WITH_RC4_128_SHA:                   \xC0 \x02; // Not in SSL3!
CIPHER_SUITE_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA:              \xC0 \x03; // Not in SSL3!
CIPHER_SUITE_ECDH_ECDSA_WITH_AES_128_CBC_SHA:               \xC0 \x04; // Not in SSL3!
CIPHER_SUITE_ECDH_ECDSA_WITH_AES_256_CBC_SHA:               \xC0 \x05; // Not in SSL3!
CIPHER_SUITE_ECDHE_ECDSA_WITH_NULL_SHA:                     \xC0 \x06; // Weak!
CIPHER_SUITE_ECDHE_ECDSA_WITH_RC4_128_SHA:                  \xC0 \x07; // Not in SSL3!
CIPHER_SUITE_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA:             \xC0 \x08; // Not in SSL3!
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_128_CBC_SHA:              \xC0 \x09; // Not in SSL3!
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_256_CBC_SHA:              \xC0 \x0A; // Not in SSL3!
CIPHER_SUITE_ECDH_RSA_WITH_NULL_SHA:                        \xC0 \x0B; // Weak!
CIPHER_SUITE_ECDH_RSA_WITH_RC4_128_SHA:                     \xC0 \x0C; // Not in SSL3!
CIPHER_SUITE_ECDH_RSA_WITH_3DES_EDE_CBC_SHA:                \xC0 \x0D; // Not in SSL3!
CIPHER_SUITE_ECDH_RSA_WITH_AES_128_CBC_SHA:                 \xC0 \x0E; // Not in SSL3!
CIPHER_SUITE_ECDH_RSA_WITH_AES_256_CBC_SHA:                 \xC0 \x0F; // Not in SSL3!
CIPHER_SUITE_ECDHE_RSA_WITH_NULL_SHA:                       \xC0 \x10; // Weak!
CIPHER_SUITE_ECDHE_RSA_WITH_RC4_128_SHA:                    \xC0 \x11; // Not in SSL3!
CIPHER_SUITE_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA:               \xC0 \x12; // Not in SSL3!
CIPHER_SUITE_ECDHE_RSA_WITH_AES_128_CBC_SHA:                \xC0 \x13; // Not in SSL3!
CIPHER_SUITE_ECDHE_RSA_WITH_AES_256_CBC_SHA:                \xC0 \x14; // Not in SSL3!
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256:           \xC0 \x23; // TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384:           \xC0 \x24; // TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_AES_128_CBC_SHA256:            \xC0 \x25; // TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_AES_256_CBC_SHA384:            \xC0 \x26; // TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_AES_128_CBC_SHA256:             \xC0 \x27; // TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_AES_256_CBC_SHA384:             \xC0 \x28; // TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_AES_128_CBC_SHA256:              \xC0 \x29; // TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_AES_256_CBC_SHA384:              \xC0 \x2A; // TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:           \xC0 \x2B; // TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:           \xC0 \x2C; // TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_AES_128_GCM_SHA256:            \xC0 \x2D; // TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_AES_256_GCM_SHA384:            \xC0 \x2E; // TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_AES_128_GCM_SHA256:             \xC0 \x2F; // TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_AES_256_GCM_SHA384:             \xC0 \x30; // TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_AES_128_GCM_SHA256:              \xC0 \x31; // TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_AES_256_GCM_SHA384:              \xC0 \x32; // TLS 1.2
CIPHER_SUITE_ECDHE_PSK_WITH_RC4_128_SHA:                    \xC0 \x33; // Not in SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_3DES_EDE_CBC_SHA:               \xC0 \x34; // Not in SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_AES_128_CBC_SHA:                \xC0 \x35; // Not in SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_AES_256_CBC_SHA:                \xC0 \x36; // Not in SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_AES_128_CBC_SHA256:             \xC0 \x37; // Not in SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_AES_256_CBC_SHA384:             \xC0 \x38; // Not in SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_NULL_SHA:                       \xC0 \x39; // Weak! No SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_NULL_SHA256:                    \xC0 \x3A; // Weak! No SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_NULL_SHA384:                    \xC0 \x3B; // Weak! No SSL3!
CIPHER_SUITE_RSA_WITH_ARIA_128_CBC_SHA256:                  \xC0 \x3C; // TLS 1.2
CIPHER_SUITE_RSA_WITH_ARIA_256_CBC_SHA384:                  \xC0 \x3D; // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_ARIA_128_CBC_SHA256:              \xC0 \x44; // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_ARIA_256_CBC_SHA384:              \xC0 \x45; // TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_ARIA_128_CBC_SHA256:          \xC0 \x48; // TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_ARIA_256_CBC_SHA384:          \xC0 \x49; // TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_ARIA_128_CBC_SHA256:           \xC0 \x4A; // TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_ARIA_256_CBC_SHA384:           \xC0 \x4B; // TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_ARIA_128_CBC_SHA256:            \xC0 \x4C; // TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_ARIA_256_CBC_SHA384:            \xC0 \x4D; // TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_ARIA_128_CBC_SHA256:             \xC0 \x4E; // TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_ARIA_256_CBC_SHA384:             \xC0 \x4F; // TLS 1.2
CIPHER_SUITE_RSA_WITH_ARIA_128_GCM_SHA256:                  \xC0 \x50; // TLS 1.2
CIPHER_SUITE_RSA_WITH_ARIA_256_GCM_SHA384:                  \xC0 \x51; // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_ARIA_128_GCM_SHA256:              \xC0 \x52; // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_ARIA_256_GCM_SHA384:              \xC0 \x53; // TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256:          \xC0 \x5C; // TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_ARIA_256_GCM_SHA384:          \xC0 \x5D; // TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_ARIA_128_GCM_SHA256:           \xC0 \x5E; // TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_ARIA_256_GCM_SHA384:           \xC0 \x5F; // TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_ARIA_128_GCM_SHA256:            \xC0 \x60; // TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_ARIA_256_GCM_SHA384:            \xC0 \x61; // TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_ARIA_128_GCM_SHA256:             \xC0 \x62; // TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_ARIA_256_GCM_SHA384:             \xC0 \x63; // TLS 1.2
CIPHER_SUITE_PSK_WITH_ARIA_128_CBC_SHA256:                  \xC0 \x64; // TLS 1.2
CIPHER_SUITE_PSK_WITH_ARIA_256_CBC_SHA384:                  \xC0 \x65; // TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_ARIA_128_CBC_SHA256:              \xC0 \x66; // TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_ARIA_256_CBC_SHA384:              \xC0 \x67; // TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_ARIA_128_CBC_SHA256:              \xC0 \x68; // TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_ARIA_256_CBC_SHA384:              \xC0 \x69; // TLS 1.2
CIPHER_SUITE_PSK_WITH_ARIA_128_GCM_SHA256:                  \xC0 \x6A; // TLS 1.2
CIPHER_SUITE_PSK_WITH_ARIA_256_GCM_SHA384:                  \xC0 \x6B; // TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_ARIA_128_GCM_SHA256:              \xC0 \x6C; // TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_ARIA_256_GCM_SHA384:              \xC0 \x6D; // TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_ARIA_128_GCM_SHA256:              \xC0 \x6E; // TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_ARIA_256_GCM_SHA384:              \xC0 \x6F; // TLS 1.2
CIPHER_SUITE_ECDHE_PSK_WITH_ARIA_128_CBC_SHA256:            \xC0 \x70; // TLS 1.2
CIPHER_SUITE_ECDHE_PSK_WITH_ARIA_256_CBC_SHA384:            \xC0 \x71; // TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_CAMELLIA_128_CBC_SHA256:      \xC0 \x72; // Not in SSL3!
CIPHER_SUITE_ECDHE_ECDSA_WITH_CA:                           \xC0 \x73; // Not in SSL3!
CIPHER_SUITE_ECDH_ECDSA_WITH_CAM:                           \xC0 \x74; // Not in SSL3!
CIPHER_SUITE_ECDH_ECDSA_WITH_CAMELLIA_256_CBC_SHA384:       \xC0 \x75; // Not in SSL3!
CIPHER_SUITE_ECDHE_RSA_WITH_CAMELLIA_128_CBC_SHA256:        \xC0 \x76; // Not in SSL3!
CIPHER_SUITE_ECDHE_RSA_WITH_CAMELLIA_256_CBC_SHA384:        \xC0 \x77; // Not in SSL3!
CIPHER_SUITE_ECDH_RSA_WITH_CAMELLIA_128_CBC_SHA256:         \xC0 \x78; // Not in SSL3!
CIPHER_SUITE_ECDH_RSA_WITH_CAMELLIA_256_CBC_SHA384:         \xC0 \x79; // Not in SSL3!
CIPHER_SUITE_RSA_WITH_CAMELLIA_128_GCM_SHA256:              \xC0 \x7A; // TLS 1.2
CIPHER_SUITE_RSA_WITH_CAMELLIA_256_GCM_SHA384:              \xC0 \x7B; // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_CAMELLIA_128_GCM_SHA256:          \xC0 \x7C; // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_CAMELLIA_256_GCM_SHA384:          \xC0 \x7D; // TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_CAMELLIA_128_GCM_SHA256:      \xC0 \x86; // TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_CAMELLI:                      \xC0 \x87; // TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_CAMELLIA:                      \xC0 \x88; // TLS 1.2
CIPHER_SUITE_ECDH_ECDSA_WITH_CAMELLIA_256_GCM_SHA384:       \xC0 \x89; // TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_CAMELLIA_128_GCM_SHA256:        \xC0 \x8A; // TLS 1.2
CIPHER_SUITE_ECDHE_RSA_WITH_CAMELLIA_256_GCM_SHA384:        \xC0 \x8B; // TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_CAMELLIA_128_GCM_SHA256:         \xC0 \x8C; // TLS 1.2
CIPHER_SUITE_ECDH_RSA_WITH_CAMELLIA_256_GCM_SHA384:         \xC0 \x8D; // TLS 1.2
CIPHER_SUITE_PSK_WITH_CAMELLIA_128_GCM_SHA256:              \xC0 \x8E; // TLS 1.2
CIPHER_SUITE_PSK_WITH_CAMELLIA_256_GCM_SHA384:              \xC0 \x8F; // TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_CAMELLIA_128_GCM_SHA256:          \xC0 \x90; // TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_CAMELLIA_256_GCM_SHA384:          \xC0 \x91; // TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_CAMELLIA_128_GCM_SHA256:          \xC0 \x92; // TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_CAMELLIA_256_GCM_SHA384:          \xC0 \x93; // TLS 1.2
CIPHER_SUITE_PSK_WITH_CAMELLIA_128_CBC_SHA256:              \xC0 \x94;
CIPHER_SUITE_PSK_WITH_CAMELLIA_256_CBC_SHA384:              \xC0 \x95;
CIPHER_SUITE_DHE_PSK_WITH_CAMELLIA_128_CBC_SHA256:          \xC0 \x96;
CIPHER_SUITE_DHE_PSK_WITH_CAMELLIA_256_CBC_SHA384:          \xC0 \x97;
CIPHER_SUITE_RSA_PSK_WITH_CAMELLIA_128_CBC_SHA256:          \xC0 \x98;
CIPHER_SUITE_RSA_PSK_WITH_CAMELLIA_256_CBC_SHA384:          \xC0 \x99;
CIPHER_SUITE_ECDHE_PSK_WITH_CAMELLIA_128_CBC_SHA256:        \xC0 \x9A; // Not in SSL3!
CIPHER_SUITE_ECDHE_PSK_WITH_CAMELLIA_256_CBC_SHA384:        \xC0 \x9B; // Not in SSL3!
CIPHER_SUITE_RSA_WITH_AES_128_CCM:                          \xC0 \x9C;  // TLS 1.2
CIPHER_SUITE_RSA_WITH_AES_256_CCM:                          \xC0 \x9D;  // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_AES_128_CCM:                      \xC0 \x9E;  // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_AES_256_CCM:                      \xC0 \x9F;  // TLS 1.2
CIPHER_SUITE_RSA_WITH_AES_128_CCM_8:                        \xC0 \xA0;  // TLS 1.2
CIPHER_SUITE_RSA_WITH_AES_256_CCM_8:                        \xC0 \xA1;  // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_AES_128_CCM_8:                    \xC0 \xA2;  // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_AES_256_CCM_8:                    \xC0 \xA3;  // TLS 1.2
CIPHER_SUITE_PSK_WITH_AES_128_CCM:                          \xC0 \xA4;  // TLS 1.2
CIPHER_SUITE_PSK_WITH_AES_256_CCM:                          \xC0 \xA5;  // TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_AES_128_CCM:                      \xC0 \xA6;  // TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_AES_256_CCM:                      \xC0 \xA7;  // TLS 1.2
CIPHER_SUITE_PSK_WITH_AES_128_CCM_8:                        \xC0 \xA8;  // TLS 1.2
CIPHER_SUITE_PSK_WITH_AES_256_CCM_8:                        \xC0 \xA9;  // TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_AES_128_CCM_8:                    \xC0 \xAA;  // TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_AES_256_CCM_8:                    \xC0 \xAB;  // TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_128_CCM:                  \xC0 \xAC;  // TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_256_CCM:                  \xC0 \xAD;  // TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_128_CCM_8:                \xC0 \xAE;  // TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_AES_256_CCM_8:                \xC0 \xAF;  // TLS 1.2
CIPHER_SUITE_ECJPAKE_WITH_AES_128_CCM_8:                    \xC0 \xFF;  // experimental
CIPHER_SUITE_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256:       \xCC \xA8; // TLS 1.2
CIPHER_SUITE_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256:     \xCC \xA9; // TLS 1.2
CIPHER_SUITE_DHE_RSA_WITH_CHACHA20_POLY:                    \xCC \xAA; // TLS 1.2
CIPHER_SUITE_PSK_WITH_CHACHA20_POLY1305_SHA256:             \xCC \xAB; // TLS 1.2
CIPHER_SUITE_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256:       \xCC \xAC; // TLS 1.2
CIPHER_SUITE_DHE_PSK_WITH_CHACHA20_POLY1305_SHA256:         \xCC \xAD; // TLS 1.2
CIPHER_SUITE_RSA_PSK_WITH_CHACHA20_POLY1305_SHA256:         \xCC \xAE; // TLS 1.2
