// Binary packets from a bundled protocol grammar, printed as a hexdump.
//
// usage: nelly -c 5 examples/dhcp.bnf
//        nelly -c 5 -s DHCP_CLIENT examples/dhcp.bnf
//        nelly -c 5 -s DHCP_SERVER examples/dhcp.bnf

include 'protocols/dhcp.bnf'

PACKET(start): DHCP;

<%post
    nelly.hexdump($$)
    print()
%>
