// Sending each generated request to a server and printing the response. The
// bundled HTTP grammar is included and HTTP_HOST and HTTP_BODY are replaced.
// &host inserts the Python variable set in the pre block.
//
// usage: nelly -v host=localhost [-v port=8080] examples/http-post.bnf

include 'constants.bnf'
include 'protocols/http.bnf'

<%pre
    import socket
    import logging

    nelly.encode = 'utf-8'

    host = $host

    try:
        port = int($port)
    except KeyError:
        port = 80

    try:
        skt
    except NameError:
        try:
            skt = socket.socket()
            skt.connect((host,port))
        except socket.error as e:
            logging.error('%s', e)
            exit()
%>

::HTTP_HOST: &host;

::HTTP_BODY: "matt";

$SEND_HTTP_REQUEST(start):
    HTTP_POST
    <%
        print($$.decode('utf-8'))
        print()

        skt.send($$)
        $* = skt.recv(1500)

        headers,body = $*.decode('utf-8').split('\r\n\r\n', 1)

        print(headers)
        print(body)
    %>;
