
include 'constants.bnf'
include 'protocols/http.bnf'

<%pre
    import socket
    import logging

    host = $host

    try:
        port = int($port)
    except KeyError:
        port = 80

    try:
        skt
    except NameError:
        try:
            skt = socket.socket()
            skt.connect((host,port))
        except socket.error as e:
            logging.error('%s', e)
            exit()
%>

::HTTP_BODY:
    "matt"
    ;

<%post
    print($$)
%>

::HTTP_HOST:
    &host
    ;

$SEND_HTTP_REQUEST(start):
    HTTP_POST <%
        print($$)
        print()

        skt.send($$.encode('utf-8'))
        $* = skt.recv(1500)

        headers,body = $*.decode('utf-8').split('\r\n\r\n', 1)

        print(headers)
        print(body)
    %>;
