<%pre

    import sys
    import socket
    import logging

    try:
        port = int($port)
    except KeyError:
        port = 8443

    skt = socket.socket()
    skt.bind(('127.0.0.1', port))

    logging.info('Listeing on %d', port)

%>

$SERVER(start): empty;

<%post
    print '--', $$
%>
