
// Usage: nelly -i examples -v path=. examples/tornado.bnf

include 'html.bnf'

<%pre
    import nelly

    import tornado.ioloop
    import tornado.web

    class MainHandler(tornado.web.RequestHandler):
        def get(self):
            self.write($_Nonterminal('TRIGGER'))

    application = tornado.web.Application([
        (r"/", MainHandler),
    ])

    application.listen(8888)
    try:
        tornado.ioloop.IOLoop.instance().start()
    except KeyboardInterrupt:
        pass
%>


NT(start): empty;

TRIGGER: 'This is Nelly!' | HTML_START;
