
<%
    import time
    import logging

    import _.py

    try:
        import OpenSSL
    except ImportError:
        logging.error('Missing Python OpenSSL library')
        fail()

    try:
        import Crypto
    except ImportError:
        logging.error('Missing Python Crypto library')
        fail()

    def dump509(sX509):
        x509 = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_ASN1, sX509)

        x509name = x509.get_subject()
        print 'X509 Name:',
        d = {}
        for (sKey,sValue) in x509name.get_components():
            d[sKey] = sValue
        print d['CN']
        print

        pkey = x509.get_pubkey()

        priv_key = OpenSSL.crypto.dump_privatekey(OpenSSL.crypto.FILETYPE_ASN1, pkey)

        _.hexdump(priv_key)

%>

VERSION: 0x03 0x01;

# Record types
TYPE_HANDSHAKE: 0x16;
TYPE_CHANGE_CIPHER_SPEC: 0x14;
