include 'protocols/http.bnf'
include 'protocols/soap.bnf'

<%pre
import sys
import string
import random
import socket
%>

::SSDP_DISCOVER:
    'M-SEARCH * HTTP/1.1' CRLF
    'Host:239.255.255.250:1900' CRLF
    'ST:' SSDP_ACTION CRLF
    'Man:"ssdp:discover"' CRLF
    'MX:3' CRLF
    CRLF
    ;

::SSDP_ACTION
    : URNS
    | UUIDS
    ;

URNS: 'urn:' URN_ACTIONS;

URN_ACTIONS
    : 'schemas:' SCHEMAS
    | 'schemas-upnp-org:' SCHEMAS
    | 'services:' LONGWORD
    | 'devices:' LONGWORD
    ;

SCHEMAS
    : 'device:InternetGatewayDevice:1'
    | 'device:' LONGWORD ':end'
    ;

UUIDS: 'uuid:' UUID_ACTIONS;

UUID_ACTIONS
    : 'schemas:' SCHEMAS
    | LONGWORD SUFFIX '::end'
    | LONGWORD SUFFIX
    ;

SUFFIX
    : <98>
    | '::upnp:rootdevice' <2>
    ;


::UPNP_HTTP_START: HTTP_START;

::HTTP_ACTION: 'POST';
::HTTP_PATH: '/';

::HTTP_CONNECTION: 'Connection: close' CRLF;

::HTTP_HEADERS
    : SOAPACTION CRLF
    ;

::SOAPACTION: 'SOAPAction: ' SERVICE_TYPE '#' SERVICE_NAME;

SERVICE_TYPE: 'n:schemas-upnp-org:service:WANIPConnection:1';

SERVICE_NAME: %random.choice(&string.ascii_letters){100,2100};

::HTTP_BODY:
    SOAP_DOC
    ;
